Updating develop custom branch to the new generation of Metagraph IDs

diff --git a/scripts/hydra b/scripts/hydra
--- a/scripts/hydra
+++ b/scripts/hydra
@@ -76,9 +76,8 @@ create_template() {
     echo "Template already exists!"
   else
     echo "Generating template $1 ..."
-    echo "Tessellation version: $CUSTOM_BRANCH_OR_COMMIT, VERSION_NAME: $VERSION_NAME_TO_USE, TEMPLATE_TAG: $TESSELATION_LAST_RELEASED_TAG"
-    g8 Constellation-Labs/currency --tag $TESSELATION_LAST_RELEASED_TAG --name="$2" --tessellation_version="$TESSELATION_LAST_RELEASED_TAG_TEMPLATE"
-    sed -i -e "s/val tessellation = .*/val tessellation = \"$VERSION_NAME_TO_USE\"/g" $2/project/Dependencies.scala
+    echo "Tessellation version: $CUSTOM_BRANCH_OR_COMMIT, VERSION_NAME: $VERSION_NAME_TO_USE"
+    g8 Constellation-Labs/currency --branch $CUSTOM_BRANCH_OR_COMMIT --name="$2" --tessellation_version="$VERSION_NAME_TO_USE"
   fi
   cd ../../
 }
@@ -217,12 +216,33 @@ check_if_project_directory_exists() {
   cd ..
 }
 
-start_containers(){
-    set_docker_compose
-    OUTPUT_YELLOW=$(tput setaf 3)
-    OUTPUT_WHITE=$(tput setaf 7)
+get_metagraph_id_from_genesis_currency_l0() {
+   for ((i = 1; i <= 11; i++)); do
+    METAGRAPH_ID=$(docker logs l0-currency-1 -n 1000 | grep "Address from genesis data is .*" | grep -o "DAG.*")
+    if [[ -z "$METAGRAPH_ID" ]]; then
+      if [ $i -eq 10 ]; then
+        echo "Could not find the METAGRAPH_ID, check the currency L0 node 1 logs"
+        exit 1
+      fi
+      echo "METAGRAPH_ID not found trying again in 30s"
+      sleep 30
+    else
+      cd ../../../
+      echo "METAGRAPH_ID found: $METAGRAPH_ID"
+      echo "Filling the .env file"
+      echo "$(sed '/METAGRAPH_ID=.*/d' .env)" > .env
+      echo "METAGRAPH_ID=$METAGRAPH_ID" >> .env
 
-    check_if_docker_is_running
+      set -o allexport
+      source .env set
+
+      cd infra/docker/currency-l0-genesis
+      break
+    fi
+  done
+}
+
+start_containers(){
     if [[ -z "$1" || "$1" == "global-l0" ]]; then
       if ! docker inspect --type=image global-l0 &>/dev/null; then
         echo "You need to build the Global L0 first"
@@ -249,13 +269,6 @@ start_containers(){
       fi
     fi
 
-    VALID_ONLY_OPTIONS="global-l0 dag-l1 currency-l0 currency-l1 monitoring"
-    BASEDIR=$(dirname "$0")
-    cd $BASEDIR
-    if [ -d "scripts" ]; then
-      cd scripts/
-    fi
-
     global_l0_url=""
     dag_l1_1_url=""
     dag_l1_2_url=""
@@ -267,13 +280,6 @@ start_containers(){
     currency_l1_2_url=""
     currency_l1_3_url=""
     grafana_url=""
-
-    if [ ! -z "$1" ]; then
-      if [[ ! $VALID_ONLY_OPTIONS =~ (^|[[:space:]])$1($|[[:space:]]) ]]; then
-        echo "You should provide a valid only option"
-        exit 1
-      fi
-    fi
 
     create_docker_custom_network
 
@@ -295,7 +301,11 @@ start_containers(){
     fi
 
     if [[ -z "$1" || "$1" == "currency-l0" ]]; then
-      run_container currency-l0 http://localhost:9400/metrics
+      run_container currency-l0-genesis http://localhost:9400/metrics
+      get_metagraph_id_from_genesis_currency_l0
+      cd ../
+
+      run_container currency-l0 http://localhost:9500/metrics
       join_l0_currency_nodes
 
       currency_l0_1_url="$OUTPUT_YELLOW Currency L0 - 1: $OUTPUT_WHITE http://localhost:9400/cluster/info"
@@ -305,6 +315,10 @@ start_containers(){
     fi
 
     if [[ -z "$1" || "$1" == "currency-l1" ]]; then
+      if [[ -z "$METAGRAPH_ID" ]]; then
+        echo "METAGRAPH_ID not found on .env file, please fill this parameter or run currency-l0"
+        exit 1
+      fi
       run_container currency-l1
       join_l1_currency_nodes
 
@@ -513,19 +527,28 @@ build() {
 
   if [[ -z "$argc_only" || "$argc_only" == "currency-l0" ]]; then
     export SHOULD_RESET_GENESIS_FILE=""
-    cd currency-l0
+    export METAGRAPH_ID=""
+    cd currency-l0-genesis
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building Currency L0 image... (NO CACHE)"
       $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
+      cd ../currency-l0
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
     else
       echo "Building Currency L0 image... (USING CACHE)"
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
+      cd ../currency-l0
       $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
     fi
     echo "Currency L0 image built"
 
     if [ ! -z "$argc_run" ]; then
       cd ../
-      run_container currency-l0 http://localhost:9400/metrics
+      run_container currency-l0-genesis http://localhost:9400/metrics
+      get_metagraph_id_from_genesis_currency_l0
+      cd ../
+
+      run_container currency-l0 http://localhost:9500/metrics
       join_l0_currency_nodes
       currency_l0_1_url="$OUTPUT_YELLOW Currency L0 - 1: $OUTPUT_WHITE http://localhost:9400/cluster/info"
       currency_l0_2_url="$OUTPUT_YELLOW Currency L0 - 2: $OUTPUT_WHITE http://localhost:9500/cluster/info"
@@ -546,6 +569,10 @@ build() {
     echo "Currency L1 image built"
 
     if [ ! -z "$argc_run" ]; then
+      if [[ -z "$METAGRAPH_ID" ]]; then
+        echo "METAGRAPH_ID not found on .env file, please fill this parameter or run currency-l0"
+        exit 1
+      fi
       cd ../
       run_container currency-l1
       join_l1_currency_nodes
@@ -615,14 +642,60 @@ build() {
 # @flag   --include_dag_l1           Includes the dag l1 layer to build/run
 # @option --only                     Start specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 start_genesis() {
- export SHOULD_RESET_GENESIS_FILE=true
- start_containers $argc_only $argc_include_dag_l1
+  set_docker_compose
+  OUTPUT_YELLOW=$(tput setaf 3)
+  OUTPUT_WHITE=$(tput setaf 7)
+  check_if_docker_is_running
+
+  BASEDIR=$(dirname "$0")
+  VALID_ONLY_OPTIONS="global-l0 dag-l1 currency-l0 currency-l1 monitoring"
+
+  cd $BASEDIR
+  if [ -d "scripts" ]; then
+    cd scripts/
+  fi
+
+  if [ ! -z "$argc_only" ]; then
+    if [[ ! $VALID_ONLY_OPTIONS =~ (^|[[:space:]])$1($|[[:space:]]) ]]; then
+      echo "You should provide a valid only option"
+      exit 1
+    fi
+  fi
+
+  set -o allexport
+  source ../.env set
+
+  export SHOULD_RESET_GENESIS_FILE=true
+  start_containers $argc_only $argc_include_dag_l1
 }
 
 # @cmd Start containers
 # @flag   --include_dag_l1           Includes the dag l1 layer to build/run
 # @option --only                     Start specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 start() {
+  set_docker_compose
+  OUTPUT_YELLOW=$(tput setaf 3)
+  OUTPUT_WHITE=$(tput setaf 7)
+  check_if_docker_is_running
+
+  BASEDIR=$(dirname "$0")
+  VALID_ONLY_OPTIONS="global-l0 dag-l1 currency-l0 currency-l1 monitoring"
+
+  cd $BASEDIR
+  if [ -d "scripts" ]; then
+    cd scripts/
+  fi
+
+  if [ ! -z "$argc_only" ]; then
+    if [[ ! $VALID_ONLY_OPTIONS =~ (^|[[:space:]])$argc_only($|[[:space:]]) ]]; then
+      echo "You should provide a valid only option"
+      exit 1
+    fi
+  fi
+
+  set -o allexport
+  source ../.env set
+
   export SHOULD_RESET_GENESIS_FILE=""
   start_containers $argc_only $argc_include_dag_l1
 }
@@ -631,6 +704,7 @@ start() {
 # @option --only                     Stop specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 stop() {
   export SHOULD_RESET_GENESIS_FILE=""
+  export METAGRAPH_ID=""
   set_docker_compose
   check_if_docker_is_running
   BASEDIR=$(dirname "$0")
@@ -647,6 +721,7 @@ stop() {
   fi
 
   if [[ -z "$argc_only" || "$argc_only" == "currency-l0" ]]; then
+    stop_container currency-l0-genesis
     stop_container currency-l0
   fi
 
@@ -668,6 +743,7 @@ stop() {
 # @option --only                      Destroy specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 destroy() {
   export SHOULD_RESET_GENESIS_FILE=""
+  export METAGRAPH_ID=""
   set_docker_compose
   check_if_docker_is_running
   BASEDIR=$(dirname "$0")
@@ -692,6 +768,7 @@ destroy() {
   fi
 
   if [[ -z "$argc_only" || "$argc_only" == "currency-l0" ]]; then
+    destroy_container currency-l0-genesis
     destroy_container currency-l0
   fi
 
